# version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mern

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
      target: builder
    container_name: backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src:/usr/src/app/src # hot reload source code
      - /usr/src/app/node_modules # prevent overwriting node_modules
    command: npm run dev
    depends_on:
      - mongo
    networks:
      - mern

  mongo:
    image: mongo:6.0
    container_name: mongo-job-application
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    networks:
      - mern

networks:
  mern:
    driver: bridge

volumes:
  mongo_data: {}
